// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcsN2xOB0dhsF3UMN76amiZnQoHWQZhA',
    appId: '1:152479873580:web:e675d2817cd967c8a22f89',
    messagingSenderId: '152479873580',
    projectId: 'feedback-form-c9f71',
    authDomain: 'feedback-form-c9f71.firebaseapp.com',
    storageBucket: 'feedback-form-c9f71.firebasestorage.app',
    measurementId: 'G-LZCT6RJ5HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALvI-SuOpIKYfcB7pcsHUqTl3V7WEINGg',
    appId: '1:152479873580:android:40a474b8d735b9d4a22f89',
    messagingSenderId: '152479873580',
    projectId: 'feedback-form-c9f71',
    storageBucket: 'feedback-form-c9f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRd1OzP5OpDijkRHANAIKScK7ykoWZrc',
    appId: '1:152479873580:ios:f479948157b8e836a22f89',
    messagingSenderId: '152479873580',
    projectId: 'feedback-form-c9f71',
    storageBucket: 'feedback-form-c9f71.firebasestorage.app',
    iosClientId:
        '152479873580-8koqetmvu9o704rrl1j9illiirqq55p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtRd1OzP5OpDijkRHANAIKScK7ykoWZrc',
    appId: '1:152479873580:ios:f479948157b8e836a22f89',
    messagingSenderId: '152479873580',
    projectId: 'feedback-form-c9f71',
    storageBucket: 'feedback-form-c9f71.firebasestorage.app',
    iosClientId:
        '152479873580-8koqetmvu9o704rrl1j9illiirqq55p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCcsN2xOB0dhsF3UMN76amiZnQoHWQZhA',
    appId: '1:152479873580:web:53036ff16d98ef46a22f89',
    messagingSenderId: '152479873580',
    projectId: 'feedback-form-c9f71',
    authDomain: 'feedback-form-c9f71.firebaseapp.com',
    storageBucket: 'feedback-form-c9f71.firebasestorage.app',
    measurementId: 'G-45JG9R3M32',
  );
}
