final List<Map<String, dynamic>> all_products = [
  {
    "name": "Corned Beef",
    "image": "assets/images/cornedbeef.jpg",
    "flavor": "",
    "price": 29.75,
    "quantity": 0,
  },
  {
    "name": "Young's Town",
    "image": "assets/images/young.jpg",
    "flavor": "",
    "price": 27.50,
    "quantity": 0,
  },
  {
    "name": "Ligo",
    "image": "assets/images/sardines2.jpg",
    "flavor": "",
    "price": 30.00,
    "quantity": 0,
  },
  {
    "name": "555",
    "image": "assets/images/sardines3.jpg",
    "flavor": "",
    "price": 28.75,
    "quantity": 0,
  },
  {
    "name": "SABA",
    "image": "assets/images/sardines6.jpg",
    "flavor": "",
    "price": 30.00,
    "quantity": 0,
  },
  {
    "name": "555 Spanish",
    "image": "assets/images/sardines5.jpg",
    "flavor": "",
    "price": 28.75,
    "quantity": 0,
  },
  {
    "name": "Spam",
    "image": "assets/images/spam.jpg",
    "flavor": "",
    "price": 73.00,
    "quantity": 0,
  },
  {
    "name": "Beef Loaf",
    "image": "assets/images/beefloap.jpg",
    "flavor": "",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Fresca Tuna",
    "image": "assets/images/fp.jpg",
    "flavor": "Lechon Paksiw",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Fresca Tuna",
    "image": "assets/images/fA.jpg",
    "flavor": "Afritada",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Fresca Tuna",
    "image": "assets/images/f1oil.jpg",
    "flavor": "flakes in oil ",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Fresca Tuna",
    "image": "assets/images/f2m.jpg",
    "flavor": "Mechado",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Fresca Tuna",
    "image": "assets/images/f3h.jpg",
    "flavor": "Hot and Spicy",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Century Tuna",
    "image": "assets/images/Ch.jpg",
    "flavor": "Hot and Spicy",
    "price": 28.75,
    "quantity": 0,
  },
  {
    "name": "Century Tuna",
    "image": "assets/images/Cf.jpg",
    "flavor": "Flakes in oil",
    "price": 33.75,
    "quantity": 0,
  },
  {
    "name": "Wow Ulam",
    "image": "assets/images/wow1.jpg",
    "flavor": "Afritada",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Holiday Beef loaf",
    "image": "assets/images/Hsmall.jpg",
    "flavor": "",
    "price": 30.75,
    "quantity": 0,
  },
  {
    "name": "Fiesta Beef loaf",
    "image": "assets/images/f.jpg",
    "flavor": "",
    "price": 31.75,
    "quantity": 0,
  },
  {
    "name": "Youngs town",
    "image": "assets/images/ymakarel.jpg",
    "flavor": "Mackerel",
    "price": 27.75,
    "quantity": 0,
  },
  {
    "name": "Uni Pak",
    "image": "assets/images/uniW.jpg",
    "flavor": "Mackerel",
    "price": 29.75,
    "quantity": 0,
  },
  {
    "name": "Ligo",
    "image": "assets/images/ligoT.jpg",
    "flavor": "Tomato",
    "price": 28.75,
    "quantity": 0,
  },
  {
    "name": "Mega",
    "image": "assets/images/Mred.jpg",
    "flavor": "Tomato",
    "price": 28.75,
    "quantity": 0,
  },

  {
    "name": "Pancit Canton",
    "flavor": "Extra Hot",
    "image": "assets/images/canton.jpg",
    "price": 15.09,
    "quantity": 0,
  },
  {
    "name": "Kolson Spaghetti",
    "flavor": "",
    "image": "assets/images/kolsonspaghetti.jpg",
    "price": 225.00,
    "quantity": 0,
  },
  {
    "name": "Lucky Me",
    "flavor": "Chicken",
    "image": "assets/images/lucky.jpg",
    "price": 12.50,
    "quantity": 0,
  },
  {
    "name": "Lucky Me",
    "flavor": "Beef",
    "image": "assets/images/lucky1.png",
    "price": 12.00,
    "quantity": 0,
  },
  {
    "name": "Golden Penny Spaghetti",
    "flavor": "",
    "image": "assets/images/goldenpennyspaghetti.jpg",
    "price": 175.00,
    "quantity": 0,
  },
  {
    "name": "Quickchow",
    "flavor": "Chicken",
    "image": "assets/images/quick.jpg",
    "price": 13.75,
    "quantity": 0,
  },
  {
    "name": "Monteagles Spaghetti",
    "flavor": "",
    "image": "assets/images/monteaglespaghetti.jpg",
    "price": 150.00,
    "quantity": 0,
  },
  {
    "name": "Quickchow",
    "flavor": "Beef",
    "image": "assets/images/quick1.jpg",
    "price": 13.00,
    "quantity": 0,
  },
  {
    "name": "daibah spaghetti",
    "flavor": "",
    "image": "assets/images/daibahspaghetti.jpg",
    "price": 135.00,
    "quantity": 0,
  },
  {
    "name": "Quickchow",
    "flavor": "Beef Hot and Spicy",
    "image": "assets/images/quick2.jpg",
    "price": 13.00,
    "quantity": 0,
  },
  {
    "name": "Cup noodles",
    "image": "assets/images/cupnoodles1.jpg",
    "price": 32.00,
    "quantity": 0,
  },
  {
    "name": "Cup noodles Sotanghon",
    "image": "assets/images/cupnoodles2.jpg",
    "price": 31.00,
    "quantity": 0,
  },
  {
    "name": "Cup Noodles Batchoy",
    "image": "assets/images/cupnoodles5.jpg",
    "price": 35.50,
    "quantity": 0,
  },
  {
    "name": "Cup Noodles Jjamppong",
    "image": "assets/images/cupnoodles6.jpg",
    "price": 35.50,
    "quantity": 0,
  },
  {
    "name": "Lucky me",
    "flavor": "Lomi",
    "image": "assets/images/luck3.webp",
    "price": 13.00,
    "quantity": 0,
  },
  {
    "name": "Lucky me",
    "flavor": "Batchoy",
    "image": "assets/images/luck2.webp",
    "price": 13.00,
    "quantity": 0,
  },
  {
    "name": "Lucky me",
    "flavor": "Bulalo",
    "image": "assets/images/luck1.jpg",
    "price": 13.00,
    "quantity": 0,
  },
  {
    "name": "Lucky me",
    "flavor": "Spicy Labuyo",
    "image": "assets/images/luck.webp",
    "price": 13.00,
    "quantity": 0,
  },
  {
    "name": "Pancit Canton",
    "flavor": "Sweet & Spicy",
    "image": "assets/images/canton2.jpg",
    "price": 12.50,
    "quantity": 0,
  },
  {
    "name": "Pancit Canton",
    "flavor": "Original",
    "image": "assets/images/canton.jpg",
    "price": 12.50,
    "quantity": 0,
  },
  {
    "name": "Xtra Big",
    "flavor": "Kalamansi",
    "image": "assets/images/cupnoodles15.jpg",
    "price": 19.50,
    "quantity": 0,
  },
  {
    "name": "Shin ",
    "flavor": "Spicy",
    "image": "assets/images/cupnoodles16.jpg",
    "price": 65.00,
    "quantity": 0,
  },
  {
    "name": "Buldak ",
    "flavor": "Hot Spicy",
    "image": "assets/images/cupnoodles17.jpg",
    "price": 63.00,
    "quantity": 0,
  },
  {
    "name": "Mi Joreng ",
    "flavor": "Hot Spicy",
    "image": "assets/images/cupnoodles18.jpg",
    "price": 67.00,
    "quantity": 0,
  },
  {
    "name": "Kari ",
    "flavor": "Hot Spicy",
    "image": "assets/images/cupnoodles19.jpg",
    "price": 56.00,
    "quantity": 0,
  },
  {
    "name": "Kolee ",
    "flavor": "Chicken",
    "image": "assets/images/cupnoodles20.jpg",
    "price": 53.00,
    "quantity": 0,
  },

  {
    "name": "Datu Puti Swan",
    "flavor": "",
    "image": "assets/images/soysauce1.jpg",
    "price": 43.09,
    "quantity": 0,
  },
  {
    "name": "Silver Swan",
    "flavor": "",
    "image": "assets/images/soysauce2.jpg",
    "price": 45.50,
    "quantity": 0,
  },
  {
    "name": "Caldereta",
    "flavor": "",
    "image": "assets/images/caldereta.jpg",
    "price": 25.50,
    "quantity": 0,
  },
  {
    "name": "Knoor",
    "flavor": "Beef",
    "image": "assets/images/knoorbeefcube.jpg",
    "price": 8.50,
    "quantity": 0,
  },
  {
    "name": "Knoor",
    "flavor": "Chicken",
    "image": "assets/images/knoorchickencube.jpg",
    "price": 8.50,
    "quantity": 0,
  },
  {
    "name": "Knoor",
    "flavor": "Pork",
    "image": "assets/images/knoorporkcube.jpg",
    "price": 8.50,
    "quantity": 0,
  },
  {
    "name": "Magic Sarap",
    "flavor": "50g",
    "image": "assets/images/magicsarap.webp",
    "price": 45.50,
    "quantity": 0,
  },
  {
    "name": "Magic Sarap",
    "flavor": "25g",
    "image": "assets/images/magicsarap1.webp",
    "price": 7.50,
    "quantity": 0,
  },
  {
    "name": "Knoor",
    "flavor": "Sampaloc",
    "image": "assets/images/knoorsampalocmix.jpg",
    "price": 19.50,
    "quantity": 0,
  },
  {
    "name": "Knoor",
    "flavor": "Sinigang",
    "image": "assets/images/knoorsinigangisda.jpg",
    "price": 17.50,
    "quantity": 0,
  },
  {
    "name": "Mamasitas",
    "flavor": "",
    "image": "assets/images/mamasitas.jpg",
    "price": 32.50,
    "quantity": 0,
  },
  {
    "name": "Menudo",
    "flavor": "",
    "image": "assets/images/menudo.jpg",
    "price": 35.50,
    "quantity": 0,
  },
  {
    "name": "Kikkoman Soy Sauce",
    "flavor": "",
    "image": "assets/images/soysauce3.jpg",
    "price": 66.50,
    "quantity": 0,
  },
  {
    "name": "Silver Swan Pouch",
    "flavor": "",
    "image": "assets/images/soysauce7.jpg",
    "price": 10.50,
    "quantity": 0,
  },
  {
    "name": "Silver Swan Small",
    "flavor": "",
    "image": "assets/images/soysauce8.jpg",
    "price": 25.50,
    "quantity": 0,
  },
  {
    "name": "Silver Swan Soy Sauce",
    "flavor": "",
    "image": "assets/images/soysauce9.jpg",
    "price": 12.50,
    "quantity": 0,
  },

  {
    "name": "Mang Thomas",
    "flavor": "",
    "image": "assets/images/soysauce10.jpg",
    "price": 29.50,
    "quantity": 0,
  },
  {
    "name": "Papa ketchup ",
    "flavor": "Sachet",
    "image": "assets/images/ketchup.jpg",
    "price": 18.50,
    "quantity": 0,
  },
  {
    "name": "Papa ketchup ",
    "flavor": "Bottle",
    "image": "assets/images/ketchup1.jpg",
    "price": 29.50,
    "quantity": 0,
  },
  {
    "name": "Papa ketchup ",
    "flavor": "Galloon",
    "image": "assets/images/ketchup2.jpg",
    "price": 56.50,
    "quantity": 0,
  },
  {
    "name": "Mafran ",
    "flavor": "",
    "image": "assets/images/ketchup3.jpg",
    "price": 23.50,
    "quantity": 0,
  },
  {
    "name": "Mang Thomas ",
    "flavor": "Sachet",
    "image": "assets/images/ketchup7.jpg",
    "price": 22.50,
    "quantity": 0,
  },
  {
    "name": "Mang Thomas Spicy",
    "flavor": "Sachet",
    "image": "assets/images/ketchup8.jpg",
    "price": 24.50,
    "quantity": 0,
  },
  {
    "name": "Del monte ",
    "flavor": "Sachet",
    "image": "assets/images/ketchup9.jpg",
    "price": 35.50,
    "quantity": 0,
  },
  {
    "name": "Kraft",
    "flavor": "",
    "image": "assets/images/soysauce16.jpg",
    "price": 55.50,
    "quantity": 0,
  },
  {
    "name": "UFC",
    "flavor": "",
    "image": "assets/images/soysauce12.jpg",
    "price": 29.50,
    "quantity": 0,
  },
  {
    "name": "MAMA SITAS",
    "flavor": "",
    "image": "assets/images/soysauce13.jpg",
    "price": 18.50,
    "quantity": 0,
  },
  {
    "name": "Soy Garlic",
    "flavor": "",
    "image": "assets/images/soysauce14.jpg",
    "price": 23.50,
    "quantity": 0,
  },

  {
    "name": "Kopiko Black",
    "flavor": "",
    "image": "assets/images/coffee3.jpg",
    "price": 10.09,
    "quantity": 0,
  },
  {
    "name": "Kopiko Blanca",
    "flavor": "",
    "image": "assets/images/coffee4.jpg",
    "price": 10.50,
    "quantity": 0,
  },
  {
    "name": "Bear Brand",
    "flavor": "",
    "image": "assets/images/bear.jpg",
    "price": 9.09,
    "quantity": 0,
  },
  {
    "name": "Alaska",
    "flavor": "",
    "image": "assets/images/alaska.jpg",
    "price": 25.00,
    "quantity": 0,
  },
  {
    "name": "San Mig Barako",
    "flavor": "",
    "image": "assets/images/coffee6.webp",
    "price": 10.00,
    "quantity": 0,
  },
  {
    "name": "Nescafe Creamy White",
    "flavor": "",
    "image": "assets/images/coffee12.jpg",
    "price": 15.00,
    "quantity": 0,
  },
  {
    "name": "Nescafe Original",
    "flavor": "",
    "image": "assets/images/coffee13.webp",
    "price": 15.00,
    "quantity": 0,
  },
  {
    "name": "Nescafe Original Extraforte",
    "flavor": "",
    "image": "assets/images/coffee14.jpg",
    "price": 88.00,
    "quantity": 0,
  },
  {
    "name": "Nescafe Classic",
    "flavor": "",
    "image": "assets/images/coffee16.jpg",
    "price": 42.00,
    "quantity": 0,
  },
  {
    "name": "Nido",
    "flavor": "",
    "image": "assets/images/milk8.jpg",
    "price": 220.00,
    "quantity": 0,
  },
  {
    "name": "Nestle",
    "flavor": "",
    "image": "assets/images/milk9.jpg",
    "price": 155.00,
    "quantity": 0,
  },
  {
    "name": "Cow Head",
    "flavor": "",
    "image": "assets/images/milk10.jpg",
    "price": 112.00,
    "quantity": 0,
  },
  {
    "name": "Ovaltine",
    "flavor": "",
    "image": "assets/images/milk11.jpg",
    "price": 120.00,
    "quantity": 0,
  },
  {
    "name": "Anlene",
    "flavor": "",
    "image": "assets/images/milk12.jpg",
    "price": 220.00,
    "quantity": 0,
  },
  {
    "name": "Ensure Gold",
    "flavor": "",
    "image": "assets/images/milk13.jpg",
    "price": 499.00,
    "quantity": 0,
  },
  {
    "name": "Sustagen",
    "flavor": "",
    "image": "assets/images/milk14.jpg",
    "price": 120.00,
    "quantity": 0,
  },
  {
    "name": "Goat Milk",
    "flavor": "",
    "image": "assets/images/milk15.jpg",
    "price": 88.00,
    "quantity": 0,
  },

  {
    "name": "Toblerone",
    "flavor": "",
    "image": "assets/images/choco1.jpg",
    "price": 120.00,
    "quantity": 0,
  },
  {
    "name": "DairyMilk",
    "flavor": "",
    "image": "assets/images/choco2.jpg",
    "price": 100.00,
    "quantity": 0,
  },
  {
    "name": "Maxx ",
    "flavor": "orange",
    "image": "assets/images/candy1.jpg",
    "price": 35.99,
    "quantity": 0,
  },
  {
    "name": "Maxx",
    "flavor": "lemon",
    "image": "assets/images/candy2.jpg",
    "price": 35.99,
    "quantity": 0,
  },
  {
    "name": "Mentos ",
    "flavor": "",
    "image": "assets/images/candy4.jpg",
    "price": 38.99,
    "quantity": 0,
  },
  {
    "name": "Fres",
    "flavor": "",
    "image": "assets/images/candy5.jpg",
    "price": 39.99,
    "quantity": 0,
  },
  {
    "name": "Sulit",
    "flavor": "",
    "image": "assets/images/candy6.jpg",
    "price": 37.99,
    "quantity": 0,
  },
  {
    "name": "Kendi",
    "flavor": "",
    "image": "assets/images/candy7.jpg",
    "price": 32.99,
    "quantity": 0,
  },
  {
    "name": "White Rabbit",
    "flavor": "",
    "image": "assets/images/candy8.jpg",
    "price": 31.99,
    "quantity": 0,
  },
  {
    "name": "Toblerone",
    "flavor": "Small",
    "image": "assets/images/candy9.jpeg",
    "price": 17.99,
    "quantity": 0,
  },
  {
    "name": "Kitkat",
    "flavor": "",
    "image": "assets/images/candy10.jpeg",
    "price": 15.99,
    "quantity": 0,
  },
  {
    "name": "ChupaChups",
    "flavor": "",
    "image": "assets/images/candy11.webp",
    "price": 7.99,
    "quantity": 0,
  },
  {
    "name": "Jelly Belly",
    "flavor": "",
    "image": "assets/images/candy12.jpg",
    "price": 33.99,
    "quantity": 0,
  },
  {
    "name": "XO",
    "flavor": "",
    "image": "assets/images/candy13.jpg",
    "price": 50.99,
    "quantity": 0,
  },
  {
    "name": "LALA",
    "flavor": "",
    "image": "assets/images/candy14.jpg",
    "price": 43.99,
    "quantity": 0,
  },
  {
    "name": "ChocoNuts",
    "flavor": "",
    "image": "assets/images/candy15.webp",
    "price": 42.99,
    "quantity": 0,
  },
  {
    "name": "VFresh",
    "flavor": "",
    "image": "assets/images/candy3.jpg",
    "price": 35.99,
    "quantity": 0,
  },
  {
    "name": "Stick O ",
    "flavor": "Chocolate",
    "image": "assets/images/choco4.jpg",
    "price": 66.99,
    "quantity": 0,
  },
  {
    "name": "Hershey",
    "flavor": "",
    "image": "assets/images/choco6.jpg",
    "price": 30.99,
    "quantity": 0,
  },
  {
    "name": "Goya ",
    "flavor": "",
    "image": "assets/images/choco7.jpg",
    "price": 55.99,
    "quantity": 0,
  },
  {
    "name": "Goya Take it",
    "flavor": "",
    "image": "assets/images/choco8.jpg",
    "price": 21.99,
    "quantity": 0,
  },
  {
    "name": "M&M",
    "flavor": "",
    "image": "assets/images/choco14.jpg",
    "price": 56.99,
    "quantity": 0,
  },

  {
    "name": "Piatoss",
    "flavor": "barbecue",
    "image": "assets/images/junkfood1.jpg",
    "price": 25.50,
    "quantity": 0,
  },
  {
    "name": "Piatoss",
    "flavor": "Cream",
    "image": "assets/images/junkfood2.jpg",
    "price": 25.50,
    "quantity": 0,
  },
  {
    "name": "Presto",
    "flavor": "Peanut Butter",
    "image": "assets/images/biscuit1.jpg",
    "price": 46.00,
    "quantity": 0,
  },
  {
    "name": "Presto",
    "flavor": "Choco Vanilla",
    "image": "assets/images/biscuit2.jpg",
    "price": 47.75,
    "quantity": 0,
  },
  {
    "name": "Lava Cake",
    "flavor": " ",
    "image": "assets/images/biscuit3.jpg",
    "price": 15.00,
    "quantity": 0,
  },
  {
    "name": "Tiger",
    "flavor": "",
    "image": "assets/images/biscuit4.jpg",
    "price": 20.75,
    "quantity": 0,
  },
  {
    "name": "Sky Flakes",
    "flavor": "",
    "image": "assets/images/biscuit10.jpg",
    "price": 7.00,
    "quantity": 0,
  },
  {
    "name": "Bingo",
    "flavor": "",
    "image": "assets/images/biscuit8.jpg",
    "price": 6.75,
    "quantity": 0,
  },
  {
    "name": "Hansel",
    "flavor": "",
    "image": "assets/images/biscuit7.jpg",
    "price": 7.00,
    "quantity": 0,
  },
  {
    "name": "Presto",
    "flavor": "Choco Vanilla",
    "image": "assets/images/biscuit2.jpg",
    "price": 43.75,
    "quantity": 0,
  },
  {
    "name": "Cream O",
    "flavor": "",
    "image": "assets/images/bis1.webp",
    "price": 23.75,
    "quantity": 0,
  },

  {
    "name": "Rebisco",
    "flavor": "",
    "image": "assets/images/bis3.jpg",
    "price": 7.75,
    "quantity": 0,
  },
  {
    "name": "Cheese Cake",
    "flavor": "",
    "image": "assets/images/bis4.jpg",
    "price": 14.75,
    "quantity": 0,
  },
  {
    "name": "Magic Flakes",
    "flavor": "",
    "image": "assets/images/bis5.webp",
    "price": 46.75,
    "quantity": 0,
  },
  {
    "name": "Hellopanda",
    "flavor": "",
    "image": "assets/images/bis6.webp",
    "price": 13.75,
    "quantity": 0,
  },
  {
    "name": "My Graham",
    "flavor": "",
    "image": "assets/images/bis7.webp",
    "price": 34.75,
    "quantity": 0,
  },
  {
    "name": "Chips delight",
    "flavor": "",
    "image": "assets/images/bis8.jpg",
    "price": 12.75,
    "quantity": 0,
  },
  {
    "name": "Choco Mucho",
    "flavor": "",
    "image": "assets/images/bis9.jpeg",
    "price": 10.75,
    "quantity": 0,
  },
  {
    "name": "Marie",
    "flavor": "",
    "image": "assets/images/bis10.webp",
    "price": 31.75,
    "quantity": 0,
  },
  {
    "name": "Sunflower cracker",
    "flavor": "",
    "image": "assets/images/bis11.webp",
    "price": 35.75,
    "quantity": 0,
  },

  {
    "name": "Mompo",
    "flavor": "200ml",
    "image": "assets/images/wine1.jpg",
    "price": 410.00,
    "quantity": 0,
  },
  {
    "name": "Tanduay",
    "flavor": "175ml",
    "image": "assets/images/tanduay1.jpg",
    "price": 115.00,
    "quantity": 0,
  },
  {
    "name": "Maria Clara",
    "flavor": "120ml",
    "image": "assets/images/wine2.jpg",
    "price": 475.00,
    "quantity": 0,
  },
  {
    "name": "Petrus",
    "flavor": "150ml",
    "image": "assets/images/wine3.jpg",
    "price": 765.75,
    "quantity": 0,
  },
  {
    "name": "Jacqueline",
    "flavor": "150ml",
    "image": "assets/images/wine6.jpg",
    "price": 809.75,
    "quantity": 0,
  },
  {
    "name": "Fontana",
    "flavor": "150ml",
    "image": "assets/images/wine5.jpg",
    "price": 910.75,
    "quantity": 0,
  },
  {
    "name": "Novellino",
    "flavor": "150ml",
    "image": "assets/images/wine7.jpg",
    "price": 790.75,
    "quantity": 0,
  },
  {
    "name": "Infranta",
    "flavor": "150ml",
    "image": "assets/images/wine8.jpg",
    "price": 590.75,
    "quantity": 0,
  },
  {
    "name": "Mango Wine",
    "flavor": "150ml",
    "image": "assets/images/wine9.jpg",
    "price": 650.75,
    "quantity": 0,
  },
  {
    "name": "Bugnay",
    "flavor": "150ml",
    "image": "assets/images/wine10.webp",
    "price": 698.75,
    "quantity": 0,
  },
  {
    "name": "Guyabano",
    "flavor": "150ml",
    "image": "assets/images/wine11.jpg",
    "price": 700.75,
    "quantity": 0,
  },
  {
    "name": "Santol",
    "flavor": "150ml",
    "image": "assets/images/wine12.jpg",
    "price": 499.75,
    "quantity": 0,
  },
  {
    "name": "Herbal Tonic",
    "flavor": "150ml",
    "image": "assets/images/wine13.jpg",
    "price": 515.75,
    "quantity": 0,
  },
  {
    "name": "Barefoot",
    "flavor": "150ml",
    "image": "assets/images/wine14.jpeg",
    "price": 525.75,
    "quantity": 0,
  },

  {
    "name": "Tide Bar",
    "flavor": "",
    "image": "assets/images/laundry1.jpg",
    "price": 30.09,
    "quantity": 0,
  },
  {
    "name": "Tide Powder ",
    "flavor": "",
    "image": "assets/images/laundry2.jpg",
    "price": 15.50,
    "quantity": 0,
  },
  {
    "name": "Tuff ",
    "flavor": "",
    "image": "assets/images/dishwashing.webp",
    "price": 111.50,
    "quantity": 0,
  },
  {
    "name": "Mr Clean ",
    "flavor": "",
    "image": "assets/images/diswashing1.jpeg",
    "price": 89.50,
    "quantity": 0,
  },
  {
    "name": "Bubble Man ",
    "flavor": "",
    "image": "assets/images/dishwashing2.jpg",
    "price": 215.50,
    "quantity": 0,
  },
  {
    "name": "Calla",
    "flavor": "",
    "image": "assets/images/dishwashing3.jpeg",
    "price": 67.50,
    "quantity": 0,
  },
  {
    "name": "Soap Sud ",
    "flavor": "",
    "image": "assets/images/dishwashing4.jpeg",
    "price": 120.50,
    "quantity": 0,
  },
  {
    "name": "Dawn",
    "flavor": "",
    "image": "assets/images/dishwashing5.jpeg",
    "price": 77.50,
    "quantity": 0,
  },
  {
    "name": "Ariel ",
    "flavor": "",
    "image": "assets/images/laundry11.jpg",
    "price": 96.00,
    "quantity": 0,
  },
  {
    "name": "Sunlight",
    "flavor": "",
    "image": "assets/images/laundry10.jpg",
    "price": 140.75,
    "quantity": 0,
  },
  {
    "name": "Tide Twin",
    "flavor": "",
    "image": "assets/images/laundry3.jpg",
    "price": 18.75,
    "quantity": 0,
  },
  {
    "name": "Surf Bar Pink",
    "flavor": "",
    "image": "assets/images/laundry4.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Wings Big",
    "flavor": "powder",
    "image": "assets/images/laundry17.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Wings",
    "flavor": "powder",
    "image": "assets/images/laundry18.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Wings bar",
    "flavor": "blue",
    "image": "assets/images/laundry19.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Wings bar ",
    "flavor": "green",
    "image": "assets/images/laundry20.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Wings bar ",
    "flavor": "orange",
    "image": "assets/images/laundry21.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Surf bar ",
    "flavor": "",
    "image": "assets/images/laundry22.jpg",
    "price": 25.75,
    "quantity": 0,
  },
  {
    "name": "Brite Wash",
    "flavor": "",
    "image": "assets/images/laundry5.jpg",
    "price": 67.75,
    "quantity": 0,
  },
  {
    "name": "Gain",
    "flavor": "",
    "image": "assets/images/laundry7.jpg",
    "price": 86.75,
    "quantity": 0,
  },
  {
    "name": "Axion",
    "flavor": "",
    "image": "assets/images/laundry8.jpg",
    "price": 52.75,
    "quantity": 0,
  },
  {
    "name": "Ultra",
    "flavor": "",
    "image": "assets/images/laundry9.jpg",
    "price": 91.75,
    "quantity": 0,
  },

  {
    "name": "Princess Bea Rice ",
    "flavor": "Half Sack",
    "image": "assets/images/rice1.jpg",
    "price": 1250.09,
    "quantity": 0,
  },
  {
    "name": "Young Chow Rice",
    "flavor": "Half Sack",
    "image": "assets/images/rice3.jpg",
    "price": 1200.50,
    "quantity": 0,
  },
  {
    "name": "Jasmine Rice",
    "flavor": "Half Sack",
    "image": "assets/images/rice4.jpg",
    "price": 1175.00,
    "quantity": 0,
  },
  {
    "name": "Golden Grain",
    "flavor": "Half Sack",
    "image": "assets/images/rice6.png",
    "price": 1120.00,
    "quantity": 0,
  },
  {
    "name": "Super angelica",
    "flavor": "Half Sack",
    "image": "assets/images/rice7.jpeg",
    "price": 1200.50,
    "quantity": 0,
  },
  {
    "name": "Harvester",
    "flavor": "Half Sack",
    "image": "assets/images/rice8.jpg",
    "price": 1070.90,
    "quantity": 0,
  },
  {
    "name": "Basmati Rice",
    "flavor": "Half Sack",
    "image": "assets/images/rice5.jpg",
    "price": 1170.00,
    "quantity": 0,
  },
  {
    "name": "Young Chow ",
    "flavor": "5kl",
    "image": "assets/images/rice2.jpg",
    "price": 260.00,
    "quantity": 0,
  },
  {
    "name": "Coconut Sugar ",
    "flavor": "",
    "image": "assets/images/rice10.jpeg",
    "price": 56.00,
    "quantity": 0,
  },
  {
    "name": "Ilovo Sugar",
    "flavor": "White",
    "image": "assets/images/sugar.jpg",
    "price": 86.00,
    "quantity": 0,
  },
  {
    "name": "White Sugar ",
    "flavor": "",
    "image": "assets/images/sugar2.jpg",
    "price": 89.00,
    "quantity": 0,
  },
  {
    "name": "Grans Sugar ",
    "flavor": "White",
    "image": "assets/images/sugar3.jpg",
    "price": 66.00,
    "quantity": 0,
  },
  {
    "name": "Marathon Sugar ",
    "flavor": "White",
    "image": "assets/images/sugar4.jpg",
    "price": 88.10,
    "quantity": 0,
  },
  {
    "name": "Sis Sugar ",
    "flavor": "White",
    "image": "assets/images/sugar6.jpg",
    "price": 96.12,
    "quantity": 0,
  },
  {
    "name": "Selati Sugar ",
    "flavor": "Brown",
    "image": "assets/images/sugar7.jpg",
    "price": 90.30,
    "quantity": 0,
  },
  {
    "name": "Super Chef ",
    "flavor": "Brown",
    "image": "assets/images/superchefbrownsugar.jpg",
    "price": 65.75,
    "quantity": 0,
  },

  {
    "name": "Tender Juicy Hotdog",
    "flavor": "",
    "image": "assets/images/frozen.jpg",
    "price": 78.09,
    "quantity": 0,
  },
  {
    "name": "Chicken Neck",
    "flavor": "1kl",
    "image": "assets/images/froozen6.jpg",
    "price": 190.09,
    "quantity": 0,
  },
  {
    "name": "Chicken Wings",
    "flavor": "1kl",
    "image": "assets/images/froozen10.jpg",
    "price": 190.09,
    "quantity": 0,
  },
  {
    "name": "Pork Ribs",
    "flavor": "1kl",
    "image": "assets/images/frozen3.jpg",
    "price": 210.50,
    "quantity": 0,
  },
  {
    "name": "Chicken Leg",
    "flavor": "1kl",
    "image": "assets/images/frozen4.jpg",
    "price": 180.00,
    "quantity": 0,
  },
  {
    "name": "Virgina Hotdog",
    "flavor": "",
    "image": "assets/images/frozen2.jpg",
    "price": 73.75,
    "quantity": 0,
  },
  {
    "name": "Chicken Breast Nuggets",
    "flavor": "1kl",
    "image": "assets/images/frozen11.jpg",
    "price": 75.75,
    "quantity": 0,
  },
  {
    "name": "Tocino Roll Pork",
    "flavor": "",
    "image": "assets/images/frozen15.jpg",
    "price": 45.75,
    "quantity": 0,
  },
  {
    "name": "Pure Foods Tocino",
    "flavor": "",
    "image": "assets/images/frozen14.jpg",
    "price": 74.75,
    "quantity": 0,
  },
  {
    "name": "Virgina Pork Tocino",
    "flavor": "",
    "image": "assets/images/frozen13.jpg",
    "price": 89.75,
    "quantity": 0,
  },
  {
    "name": "Egg Tray ",
    "flavor": "",
    "image": "assets/images/egg.webp",
    "price": 270.75,
    "quantity": 0,
  },
  {
    "name": "Tender Juicy Hotdog",
    "flavor": "",
    "image": "assets/images/frozen12.jpg",
    "price": 69.75,
    "quantity": 0,
  },
  {
    "name": "Longganisa",
    "flavor": "",
    "image": "assets/images/longganisa.webp",
    "price": 67.75,
    "quantity": 0,
  },
  {
    "name": "FrenchFries",
    "flavor": "",
    "image": "assets/images/frenchfries.jpg",
    "price": 115.75,
    "quantity": 0,
  },
  {
    "name": "fishball",
    "flavor": "",
    "image": "assets/images/fishball.webp",
    "price": 59.75,
    "quantity": 0,
  },

  {
    "name": "Sweet Ham ",
    "flavor": "",
    "image": "assets/images/ham.webp",
    "price": 59.75,
    "quantity": 0,
  },
  {
    "name": "Brown hotdog ",
    "flavor": "",
    "image": "assets/images/brownhotdog.webp",
    "price": 78.75,
    "quantity": 0,
  },

  {
    "name": "Bioderm ",
    "flavor": "Blue",
    "image": "assets/images/soap2.jpg",
    "price": 23.09,
    "quantity": 0,
  },
  {
    "name": "Dove White",
    "flavor": "",
    "image": "assets/images/soap10.jpg",
    "price": 30.50,
    "quantity": 0,
  },
  {
    "name": "Safe Guard Sachet",
    "flavor": "",
    "image": "assets/images/soap5.jpg",
    "price": 20.00,
    "quantity": 0,
  },
  {
    "name": "Sunsilk",
    "flavor": "",
    "image": "assets/images/soap6.jpg",
    "price": 41.75,
    "quantity": 0,
  },
  {
    "name": "Keratin",
    "flavor": "",
    "image": "assets/images/soap7.jpg",
    "price": 8.00,
    "quantity": 0,
  },
  {
    "name": "Palmolive",
    "flavor": "",
    "image": "assets/images/soap8.jpg",
    "price": 8.00,
    "quantity": 0,
  },
  {
    "name": "Sulfur",
    "image": "assets/images/soap9.jpg",
    "price": 45.00,
    "quantity": 0,
  },
  {
    "name": "Bioderm",
    "flavor": "pink",
    "image": "assets/images/bioderm.png",
    "price": 41.20,
    "quantity": 0,
  },
  {
    "name": "dove",
    "flavor": "pink",
    "image": "assets/images/dove4.png",
    "price": 61.10,
    "quantity": 0,
  },
  {
    "name": "Gluta C",
    "flavor": "",
    "image": "assets/images/gluta.png",
    "price": 31.20,
    "quantity": 0,
  },
  {
    "name": "Niacinamide",
    "flavor": "Pink",
    "image": "assets/images/niacinamide.png",
    "price": 29.10,
    "quantity": 0,
  },
  {
    "name": "Safeguard",
    "flavor": "pink",
    "image": "assets/images/safeguard.png",
    "price": 42.50,
    "quantity": 0,
  },
  {
    "name": "Safeguard",
    "flavor": "brown",
    "image": "assets/images/safeguard1.png",
    "price": 42.90,
    "quantity": 0,
  },
  {
    "name": "Safeguard",
    "flavor": "Green",
    "image": "assets/images/safeguard2.png",
    "price": 43.50,
    "quantity": 0,
  },
  {
    "name": "Safeguard",
    "flavor": "Yellow",
    "image": "assets/images/safeguard3.png",
    "price": 43.50,
    "quantity": 0,
  },
  {
    "name": "Silka pack",
    "flavor": "",
    "image": "assets/images/silka.png",
    "price": 18.00,
    "quantity": 0,
  },
  {
    "name": "Silka",
    "flavor": "Orange",
    "image": "assets/images/silka2.png",
    "price": 17.00,
    "quantity": 0,
  },
  {
    "name": "Silka",
    "flavor": "Green",
    "image": "assets/images/silka3.png",
    "price": 17.00,
    "quantity": 0,
  },
  {
    "name": "Niacinamide",
    "flavor": "black",
    "image": "assets/images/niacinamide2.png",
    "price": 25.00,
    "quantity": 0,
  },

  {
    "name": "Pancit Canton",
    "flavor": "Extra Hot",
    "image": "assets/images/canton.jpg",
    "price": 23.09,
    "quantity": 0,
  },
  {
    "name": "Lucky Me",
    "flavor": "Chicken",
    "image": "assets/images/lucky.jpg",
    "price": 25.50,
    "quantity": 0,
  },
  {
    "name": "Lucky Me",
    "flavor": "Beef",
    "image": "assets/images/lucky1.png",
    "price": 30.00,
    "quantity": 0,
  },
  {
    "name": "Quickchow",
    "flavor": "Chicken",
    "image": "assets/images/quick.jpg",
    "price": 28.75,
    "quantity": 0,
  },
  {
    "name": "Quickchow",
    "flavor": "Beef",
    "image": "assets/images/quick1.jpg",
    "price": 15.00,
    "quantity": 0,
  },
  {
    "name": "Quickchow",
    "flavor": "Beef Hot and Spicy",
    "image": "assets/images/quick2.jpg",
    "price": 50.00,
    "quantity": 0,
  },
  {
    "name": "Tuna",
    "image": "assets/images/spam.jpg",
    "price": 20.00,
    "quantity": 0,
  },
  {
    "name": "Mackerel",
    "image": "assets/images/spam.jpg",
    "price": 35.00,
    "quantity": 0,
  },
  {
    "name": "Hotdog",
    "image": "assets/images/spam.jpg",
    "price": 35.00,
    "quantity": 0,
  },
  {
    "name": "Ouhahah",
    "image": "assets/images/spam.jpg",
    "price": 35.00,
    "quantity": 0,
  },
];
